dist: trusty
sudo: required
language: cpp

compiler:
  - clang-3.6
  - gcc-4.9
  - g++-4.9

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libopenal-dev libalut-dev
  - sudo apt-get install -y libxcb-image0
  - sudo apt-get install -y libudev-dev
  - sudo apt install --reinstall libudev1

  
# Build steps
script:
  - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-4.9 /usr/bin/g++
  - mkdir build
  - cd build
  - cmake .. && make



