language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc-4.9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc-5
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc-6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env: MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc-7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env: MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: linux
      dist: trusty
      sudo: required
      compiler: clang-3.8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
      env:
        - MATRIX_EVAL="CC=clang-3.8 && CXX=clang++-3.8"
    - os: linux
      dist: trusty
      sudo: required
      compiler: clang-3.9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.9
          packages:
            - clang-3.9
      env:
        - MATRIX_EVAL="CC=clang-3.9 && CXX=clang++-3.9"
    - os: linux
      dist: trusty
      sudo: required
      compiler: clang-5.0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
    - os: osx
      osx_image: xcode9
    - os: osx
      osx_image: xcode8

before_install:
  - eval "${MATRIX_EVAL}"
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sudo apt-get update -qq ; fi
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sudo apt-get install -y libopenal-dev libalut-dev ; fi
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sudo apt-get install -y libxcb-image0 ; fi
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sudo apt-get install -y libudev-dev ; fi
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sudo apt install --reinstall libudev1 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget http://www.sfml-dev.org/files/SFML-2.4.0-osx-clang.tar.gz; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then tar xf SFML-2.4.0-osx-clang.tar.gz; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo cp -r SFML-2.4.0-osx-clang/lib/* /usr/local/lib/.; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo cp -r SFML-2.4.0-osx-clang/include/* /usr/local/include/.; fi

  
# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. && make



