dist: trusty
sudo: required
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

before_install:
  - eval "${MATRIX_EVAL}"
  - sudo apt-get update -qq
  - sudo apt-get install -y libopenal-dev libalut-dev
  - sudo apt-get install -y libxcb-image0
  - sudo apt-get install -y libudev-dev
  - sudo apt install --reinstall libudev1

  
# Build steps
script:
  - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-4.9 /usr/bin/g++
  - mkdir build
  - cd build
  - cmake .. && make



